version: '3'

services:
  web:
    build: .
    command: bash -c "python3 /code/djangoproxy/manage.py migrate --noinput && python3 /code/djangoproxy/manage.py runserver 0.0.0.0:8000 && python3 /code/djangoproxy/manage.py collectstatic --noinput"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery:
    build: .
    command: bash -c "cd djangoproxy/ && celery -A djangoproxy worker -B --loglevel=info --concurrency=10"
    volumes:
      - .:/code