# Generated by Django 3.1 on 2020-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0003_proxy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="proxy",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
