# Generated by Django 3.1 on 2020-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0004_auto_20200820_2047"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxySource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "HTTP"), (1, "HTTPS"), (2, "SOCKS"), (3, "SOCKS5")]
                    ),
                ),
                ("url", models.CharField(max_length=1000)),
            ],
        ),
    ]
